ProjectPythia/cookbook-template

- environment.yml
Remove unnecessary specs in `environment.yml` for general template usage.
Discussion:
- Do we explicitly include `pre-commit`, lint/formatters, as a "requirement" for the infrastructure we want to provide or encourage?
- Do we explicitly include `pythia-datasets`, or otherwise document its usage and availability?
- Looks like with @kmpaul's work, we can rely on getting the theme from conda-forge?
> Cleanup template `environment.yml`

- CONTRIBUTING.md
- README.md
Here's a first draft of the Contributor's Guide. The last step involves transferring the cookbook repo to this organization and adding the author as a member or outside collaborator, which should work fine for the hackathon.
> Add Contributor's Guide

- .github/workflows/deploy-book.yml
- notebooks/landing-page.md
An attempt to address #9 by switching to using https://github.com/actions/download-artifact rather than https://github.com/dawidd6/action-download-artifact for the `deploy-book.yml` workflow.
This *should* work ok because the upload and download steps occur within the same workflow.
(Also gets rid of the dumb text edit introduced in #15)
> Different action

- README.md
The badges on the README page from #18 are not showing any status because the `build-book` and `link-checker` workflows are never run directly (rather they are called as reusable actions by other workflows).
This PR replaces them with a status badge for the `nightly-build` workflow.
> Use status badge for nightly-build action

- notebooks/_config.yml
This will need to be done in all existing cookbooks as well
> Change cookbook navbar link to new domain

- README.md
This fixes the path for the status badge and a few other out-of-date references to ProjectPythiaTutorials
> Fix badge path

- README.md
The link in the badge will need to updated for each cookbook that uses this template, just like the `nightly-build` badge.
> Add binder badge to README

- _config.yml
This lets us grab the thumbnail image for the gallery with more flexibility as well as the gallery tags (for both domain and packages).
Related to https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/issues/32
> Update _config.yml to include keys for gallery cards

- .github/workflows/nightly-build.yaml
This PR should ensure that the `nightly-build` action only runs on this repository, not on personal forks.
This will avoid wasting lots of CI resources on duplicate builds (once we get this change pushed out to all the Cookbook repos).
> Do not run the nightly-build on forks of the repo

- environment.yml
Trying to address #100 following @jnmorley's suggestion: here we pin `jupyter_server<2` to see if that gets rid of the version conflict for `jsonschema`
> pin jupyter_server to < 2

- _config.yml
Super minor PR
Got a path error in the `_config.yml` for the `favicon.ico` path when building a cookbook locally. 
Updated `images/icons/favicon.ico` -> `notebooks/images/icons/favicon.ico`
> Favicon Path Fix

- .github/dependabot.yml
- .github/workflows/nightly-build.yaml
- .github/workflows/publish-book.yaml
- .github/workflows/trigger-link-check.yaml
- .github/workflows/trigger-preview.yaml
- .isort.cfg
- .pre-commit-config.yaml
- README.md
- _config.yml
- Added .pre-commit config yaml file, which is a copy of the [Pithia Foundations pre-commit config](https://github.com/ProjectPythia/pythia-foundations/blob/main/.pre-commit-config.yaml)
- Ran pre-commit on existing files in the cookbook template
cc @brian-rose
> pre-commit

- notebooks/notebook-template.ipynb
Link checker flagged a broken link in the template notebook, see [here](https://github.com/ProjectPythia/cookbook-template/actions/runs/4463605301/jobs/7838983633#step:7:48)
This should fix it. 
In general we should avoid specific links like <https://the-turing-way.netlify.app/welcome.html> wherever possible, in favor of top-level links like <https://the-turing-way.netlify.app> to avoid these kinds of failures when external sites get reorganized.
> Fix broken link

- .gitignore
@brian-rose I haven't taken a look to confirm this wouldn't break any existing machinery yet; I'll try to go test that before getting anything in. It would be nice if this can work and we can build cookbooks and make changes to repos without having to delete+rebuild, stash, or otherwise work around `_build/` floating around.
> Add _build to gitignore

- _config.yml
- notebooks/notebook-template.ipynb
Test to try to address the problem identified in https://github.com/ProjectPythia/gridding-cookbook/issues/16: that errors in notebooks should raise errors in the book build.
There is a relevant flag in myst-nb called `nb_execution_raise_on_error`. Currently it's not exposed directly through jupyter-book (https://github.com/executablebooks/jupyter-book/issues/2011) but I *think* we can set it anyway through the section in the config file
```
sphinx:
config:
```
where we can set arbitrary sphinx options.
I put a deliberate error into the template notebook here to see if it triggers a failure.
> Try setting myst flag to raise on notebook error

- environment.yml
> try removing jupyter_server version pin

- CITATION.cff
- README.md
- _config.yml
- _gallery_info.yml
- _toc.yml
- notebooks/how-to-cite.md
Template of changes necessary in each Cookbook repo now.
> changes based on DOI infrastructure

- _config.yml
This PR flags the link-checker to ignore links `https://zenodo.org/badge/*`
This will resolve the problem of new Cookbooks starting out life with built-in link checker failures until their "first release" when the Zenodo DOI badge becomes valid.
I don't think there's much danger in not checking these links.
> Ignore zenodo badge links

- environment.yml
I don't think there's any need to explicitly include `jupyter_server` in the environment file. It's a Jupyter dependency and best to let conda/mamba sort it out and keep our env file as clean as possible.
> Simplify environment by removing jupyter_server

- .pre-commit-config.yaml
As suggested by @dopplershift, due to the continued aggravation of pre-commit opening PRs that include pre-release alpha versions of prettier, this PR just removes prettier entirely from our pre-commit config.
> Remove prettier from pre-commit
